# Generated by Django 5.2.8 on 2025-11-26 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre único de la especie de alga.', max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción opcional de la especie.', null=True)),
                ('proporcion_conversion', models.DecimalField(decimal_places=2, help_text='Ejemplo: 6.00 para una proporción 6:1 (húmedo a seco).', max_digits=5)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha en que la especie fue registrada.')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Última modificación del registro.')),
            ],
        ),
    ]
