# Generated by Django 5.2.8 on 2025-11-26 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UsuariosApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(help_text='Tipo de acción ejecutada (crear, editar, eliminar...).', max_length=50)),
                ('modulo', models.CharField(help_text='Módulo o entidad afectada por la acción.', max_length=100)),
                ('detalle', models.TextField(blank=True, help_text='Detalle descriptivo opcional de la acción realizada.', null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que ocurrió la acción.')),
                ('usuario', models.ForeignKey(blank=True, help_text='Usuario responsable de la acción (puede ser NULL).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='UsuariosApp.usuariosmodels')),
            ],
        ),
    ]
