# Generated by Django 5.2.8 on 2025-11-26 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('EspecieApp', '0001_initial'),
        ('UsuariosApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(help_text='Nombre del cliente asociado al contrato.', max_length=200)),
                ('tonelaje_total', models.DecimalField(decimal_places=2, help_text='Tonelaje total comprometido en el contrato.', max_digits=10)),
                ('fecha_inicio', models.DateField(help_text='Fecha de inicio del contrato.')),
                ('fecha_fin', models.DateField(help_text='Fecha de término del contrato.')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha en que el contrato fue creado.')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Última fecha de modificación del contrato.')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='activo', help_text='Estado actual del contrato.', max_length=20)),
                ('actualizado_por', models.ForeignKey(help_text='Usuario que realizó la última actualización.', on_delete=django.db.models.deletion.PROTECT, related_name='contratos_actualizados', to='UsuariosApp.usuariosmodels')),
                ('creado_por', models.ForeignKey(help_text='Usuario que registró el contrato.', on_delete=django.db.models.deletion.PROTECT, related_name='contratos_creados', to='UsuariosApp.usuariosmodels')),
            ],
        ),
        migrations.CreateModel(
            name='EntregaContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.DateField(help_text='Mes correspondiente a la entrega (usar día 1).')),
                ('toneladas_requeridas', models.DecimalField(decimal_places=2, help_text='Kilogramos que deben ser entregados en el mes.', max_digits=10)),
                ('toneladas_cumplidas', models.DecimalField(decimal_places=2, default=0, help_text='Kilogramos efectivamente entregados.', max_digits=10)),
                ('compromiso_sin_stock', models.BooleanField(default=False, help_text='Indica si la entrega fue comprometida sin stock disponible.')),
                ('fecha_limite', models.DateField(blank=True, help_text='Fecha límite de cumplimiento cuando se compromete sin stock.', null=True)),
                ('contrato', models.ForeignKey(help_text='Contrato al cual pertenece esta entrega.', on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='ContratoApp.contrato')),
                ('especie', models.ForeignKey(help_text='Especie de alga correspondiente a esta entrega.', on_delete=django.db.models.deletion.PROTECT, related_name='entregas', to='EspecieApp.especie')),
            ],
        ),
    ]
