# Generated by Django 5.2.5 on 2025-11-22 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UsuariosApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=200)),
                ('tonelaje_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='activo', max_length=20)),
                ('actualizado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos_actualizados', to='UsuariosApp.usuariosmodels')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos_creados', to='UsuariosApp.usuariosmodels')),
            ],
        ),
        migrations.CreateModel(
            name='EntregaContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.DateField()),
                ('toneladas_requeridas', models.DecimalField(decimal_places=2, max_digits=10)),
                ('toneladas_cumplidas', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='ContratoApp.contrato')),
            ],
        ),
    ]
