# Generated by Django 5.2.8 on 2025-11-23 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('RolApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuariosModels',
            fields=[
                ('UsuarioID', models.AutoField(primary_key=True, serialize=False, verbose_name='Id del usuario')),
                ('Username', models.CharField(db_column='Username', error_messages={'unique': 'Intente con otro nombre de usuario'}, max_length=30)),
                ('Password', models.CharField(db_column='Password', max_length=200)),
                ('Email', models.EmailField(db_column='Email', error_messages={'unique': 'Este email ya esta siendo ocupado'}, max_length=254)),
                ('Nombre', models.CharField(db_column='Nombre', max_length=30)),
                ('Apellido', models.CharField(db_column='Apellido', max_length=40)),
                ('Rut', models.CharField(db_column='Rut', error_messages={'unique': 'Este rut ya esta siendo ocupado'}, max_length=10)),
                ('Telefono', models.CharField(db_column='Telefono', max_length=20)),
                ('EstadoUsuario', models.BooleanField(db_column='EstadoUsuario', verbose_name='Estado del usuario')),
                ('FechaCreacion', models.DateTimeField(auto_now_add=True, db_column='FechaCreacion', verbose_name='Fecha de creacion')),
                ('Rol', models.ForeignKey(blank=True, db_column='RolId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Usuario', to='RolApp.rolmodels')),
            ],
            options={
                'db_table': 'Usuarios',
                'constraints': [models.UniqueConstraint(fields=('Username',), name='unique_username'), models.UniqueConstraint(fields=('Email',), name='unique_email'), models.UniqueConstraint(fields=('Rut',), name='unique_rut')],
            },
        ),
    ]
