# Generated by Django 5.2.5 on 2025-11-22 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RolModels',
            fields=[
                ('RolId', models.AutoField(primary_key=True, serialize=False, verbose_name='Rol Id')),
                ('NombreRol', models.CharField(db_column='NombreRol', max_length=20, verbose_name='Nombre del rol')),
                ('DescripcionRol', models.CharField(db_column='DescripcionRol', max_length=100, verbose_name='Descripcion del rol')),
                ('PermisoVerDashboard', models.BooleanField(db_column='PermisoVerDashboard', verbose_name='Permiso de ver dashboard')),
                ('PermisoEditarStock', models.BooleanField(db_column='PermisoEditarStock', verbose_name='Permiso de editar stock')),
                ('PermisoCrearContratos', models.BooleanField(db_column='PermisoCrearContratos', verbose_name='Permiso de crear contratos')),
            ],
            options={
                'db_table': 'Rol',
            },
        ),
    ]
